services:
  sampleapp:
   image: sampleapp:latest

  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    volumes:
      - ./volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sample

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_SECURITY_ADMIN_USER=admin
    ports:
      - 3000:3000